GRANT SELECT ON Bank TO c23csa71;
GRANT INSERT ON Bank TO c23csa71;
GRANT DELETE ON Bank TO c23csa71;

REVOKE SELECT ON Bank FROM c23csa71;
REVOKE INSERT ON Bank FROM c23csa71;
REVOKE DELETE ON Bank FROM c23csa71;

GRANT ALL PRIVILEGES ON Bank TO c23csa71;

REVOKE ALL PRIVILEGES ON Bank FROM c23csa71;
SELECT * FROM c23csa71.Bank;

DELETE FROM c23csa71.Bank
WHERE bankname = 'Axis Bank';
